# Generated by Django 3.2 on 2021-12-08 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='caught_by',
            field=models.ManyToManyField(blank=True, related_name='caught', to=settings.AUTH_USER_MODEL),
        ),
    ]
